Clueless-Community/collegeAPI

- main.py
- src/filters.py
Added Medical College filters and fixed multiple state filtering with state names having spaces in between.
Solves issue: #25
> Added Medical Colleges filters

- data/allEngineeringColleges.json
there was a typo in the college name ,this commit  just rectifies the spelling error
> correct the spelling mistake

- data/allManagementColleges.json
- data/nirfManagementColleges.json
- main.py
- src/filters.py
1. Endpoint to fetch the list of all management colleges in India
2. Build an endpoint to fetch the list of NIRF ranked management colleges.
*Special thanks to @nikhil25803 and obviously the entire clueless community for giving me this wonderful opportunity to contribute.*
> Management Colleges Added with NIRF Ranking And To Fetch Via City And State

- README.md
Steps
----
From `main.py` made list of endpoints 
Added them in readme with similar description from existing 
closes #41
> Updated the new endpoints in the README.md

- data/allNirfColleges.json
- helpers/allNirfColleges.py
- main.py
> Added endpoint to fetch all NIRF colleges

- data/allEngineeringColleges.json
Added Trinity Institute Of Technology & Research, Bhopal
> Add new College details

- data/allEngineeringColleges.json
Updated all D.Y Patil Colleges based in pune for Engineering
> Added 4 new colleges

- data/allEngineeringColleges.json
> added engineering colleges in siliguri

- data/allEngineeringColleges.json
- main.py
**College Name Added** 
AISSMS college was missing from engineering college section and I have added it.
@nikhil25803 can you have a look through it ?
> New college name added

- data/allEngineeringColleges.json
Two reputed Engineering colleges in Kolkata, West Bengal have been added.
> Added two colleges in Kolkata

- data/nirfDentalColleges.json
- helpers/nirfDentalColleges.py
- main.py
Files modified : 
1. main.py
2. helpers/nirfDentalColleges.py
3. data/nirfDentalColleges.json
Link to issue that this PR solves : https://github.com/Clueless-Community/collegeAPI/issues/54
> Issue #54 Endpoint to fetch all the NIRF ranked Dental college

- data/nirfDentalColleges.json
- helpers/nirfDentalColleges.py
Files modified : 
> collegeAPI/helpers/nirfDentalColleges.py
> collegeAPI/data/nirfDentalColleges.json
> Issue #54 Update helper for getting NIRF ranked dental colleges

- data/nirfLawCollegesRanked.json
- helpers/nirfLawCollegesRanked.py
- main.py
Files modified : 
> collegeAPI/main.py
> collegeAPI/helpers/nirfLawCollegesRanked.py
> collegeAPI/data/nirfLawCollegesRanked.json
> Issue #58 Add Endpoint to get NIRF Ranked Law Colleges

- data/allEngineeringColleges.json
- src/filters.py
**filters.py** was using same computation to check state and city in json file it can be done with the help of function instead
Added one function which just passes state and city arguments to function and reduced overhead 
can you have a look @nikhil25803
> Function concept is used to tackle line of code in filters.py

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/PULL_REQUEST_TEMPLATE.md
Added the pull request template and issue templates for docs, feature requests, bugs and others
Fixes #89
> feat: Add pr template and issue templates 

- data/allArchitectureColleges.json
- helpers/allArchitectureColleges.py
- main.py
- src/filters.py
- I added the list of all the participated architecture colleges.
- Stored the scrapped data in data folder in JSON format and the scrapper in the helpers folder.
- Define the endpoint as /architecture_colleges
- I made the response with the names of the colleges along with their city, and state.
> Added endpoints for participating architecture colleges

- data/nirtopfuniversity.json
- helpers/nirftopuniversity.py
- main.py
Added top NIRF ranked universities of India.
---
Fixes #(issue_number)
---
- [ ✓] New feature (non-breaking change which adds functionality)
---
- [ ✓] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ✓] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/collegeAPI/pulls) for the same update/change?
- [ ✓] I have performed a self-review of my own code
- [✓ ] I have commented my code, particularly in hard-to-understand areas
- [✓ ] I have made corresponding changes needed to the documentation
> Added Top Nirf ranked universities

- src/filters.py
Changes from line 94 to 99
---
Fixes #(121)
---
---
> Code updated

- README.md
- data/nirfAllParticipatingColleges22.json
- helpers/nirfParticipatingInstitutes.py
- main.py
Scraped the college list from [here](https://www.nirfindia.org/2022/OverallRankingALL.html)
---
Fixes #127
---
---
> add /all endpoint

- main.py
- src/filters.py
Filter for all Nirf Colleges
---
Fixes https://github.com/Clueless-Community/collegeAPI/issues/124
---
---
> Filter all nirfcolleges

- main.py
---
Fixes #(issue_number)
---
---
> feat: added api description

- main.py
endpoint for nirf ranked law colleges
---
Fixes https://github.com/Clueless-Community/collegeAPI/issues/125
---
---
> added endpoint for nirf ranked law colleges

- main.py
- src/filters.py
> Filter colleges by state city

- main.py
Tags are added to all endpoints in main.py file. Every tag is according to the endpoint.
---
Fixes #(158)
---
---
> Added tag to each endpoint

- README.md
Resolves (#161). Updating endpoints in `README.md` to cover all endpoints in `main.py`
---
Fixes #161
---
---
> Adding missing endpoints to the README.md file (#161)

- main.py
- src/filters.py
Signed-off-by: Athar Ali Khan <atharali.khan319@gmail.com>
Added endpoints to filter law colleges by state and city
---
Fixes #164 
---
---
> Added api to filter law college by state and city
